name: CI - Validaci칩n Contador Web

on:
  push:
    branches: [main]  # Se ejecuta en cada push a main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Simular validaci칩n de c칩digo
      run: echo "Todo correcto: Archivos encontrados y estructura v치lida."
