name: CI - Validación Contador Web

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Validar existencia de archivos esenciales
      run: |
        if [ -f index.html ] && [ -f style.css ] && [ -f main.js ]; then
          echo "✅ Todos los archivos esenciales están presentes."
        else
          echo "❌ Error: Faltan archivos esenciales."
          exit 1
        fi

    - name: Finalización exitosa
      run: echo "🚀 Validación completada con éxito."
